"use client";

import { useState } from "react";
import Link from "next/link";
import { BookOpen, History, Layers, Target, FileCode, CheckCircle2 } from "lucide-react";
import { CourseInput } from "@/components/CourseInput";
import { useCourseStorage } from "@/hooks/useCourseStorage";

const EXAMPLE_GOALS = [
  "Learn backend with Node.js and PostgreSQL",
  "Backend development with Rust",
  "React + TypeScript from scratch",
  "System design for interviews",
];

export default function HomePage() {
  const [goal, setGoal] = useState("");
  const { savedCourses } = useCourseStorage();

  return (
    <div className="min-h-screen flex flex-col">
      <header className="border-b border-[var(--border)] bg-white/80 backdrop-blur-sm px-4 py-4">
        <div className="max-w-4xl mx-auto flex items-center justify-between">
          <Link
            href="/"
            className="flex items-center gap-2 font-semibold text-[var(--foreground)]"
          >
            <BookOpen className="h-6 w-6 text-[var(--primary)]" />
            DevPath AI
          </Link>
          {savedCourses.length > 0 && (
            <Link
              href="/saved"
              className="flex items-center gap-2 rounded-lg px-3 py-2 text-sm font-medium text-slate-600 hover:bg-slate-100 hover:text-slate-900 transition"
            >
              <History className="h-4 w-4" />
              Saved ({savedCourses.length})
            </Link>
          )}
        </div>
      </header>

      <main className="flex-1 flex flex-col items-center justify-center px-4 py-12 sm:py-16">
        <div className="w-full max-w-2xl mx-auto">
          {/* Hero */}
          <div className="text-center mb-8">
            <h1 className="text-3xl sm:text-4xl font-extrabold tracking-tight text-[var(--foreground)]">
              Your self-learning path, generated by AI
            </h1>
            <p className="mt-3 text-base text-slate-600 max-w-lg mx-auto">
              Enter a learning goal and get a structured course with phases, projects, and resources.
            </p>
            <div className="mt-5 flex flex-wrap items-center justify-center gap-x-4 gap-y-1 text-sm text-slate-500">
              <span className="inline-flex items-center gap-1.5">
                <Layers className="h-4 w-4 text-[var(--primary)]" />
                Phases
              </span>
              <span className="inline-flex items-center gap-1.5">
                <Target className="h-4 w-4 text-[var(--primary)]" />
                Projects
              </span>
              <span className="inline-flex items-center gap-1.5">
                <FileCode className="h-4 w-4 text-[var(--primary)]" />
                Resources
              </span>
              <span className="inline-flex items-center gap-1.5">
                <CheckCircle2 className="h-4 w-4 text-[var(--primary)]" />
                Checkpoints
              </span>
            </div>
          </div>

          {/* Input card */}
          <div className="rounded-2xl bg-white p-6 shadow-lg ring-1 ring-black/5">
            <CourseInput goal={goal} setGoal={setGoal} />
            <p className="mt-4 text-xs text-slate-500 text-center">
              Try an example below, or type your own goal.
            </p>
            <div className="mt-3 flex flex-wrap justify-center gap-2">
              {EXAMPLE_GOALS.map((example) => (
                <button
                  key={example}
                  type="button"
                  onClick={() => setGoal(example)}
                  className="rounded-full border border-slate-200 bg-slate-50 px-3 py-1.5 text-xs font-medium text-slate-700 hover:border-[var(--primary)] hover:bg-[var(--primary)]/10 hover:text-[var(--primary)] transition"
                >
                  {example}
                </button>
              ))}
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}
